title: Arthur Burns & Son
email: enquiries@mikeraynham.co.uk
description: Suppliers of newly quarried and reclaimed natural stone paving, crazy paving, walling & coping stone.
baseurl: ""
url: "http://www.arthurburns.co.uk"
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

page_gen:
  - index_files: true
    data: gallery
    name: SectionDir
    template: gallery_item
    dir: galleries

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
